Web/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Web.Common;
using System.Threading.Tasks;
using Web.Models.Settings;
using Services.Data;

namespace Web.Controllers
{
    [Authorize(Roles ="Admin")]
    public class SettingsController : Controller
    {
        private readonly IMemoryCache _memoryCache;
        private readonly ISettingService _settingService;

        public SettingsController(IMemoryCache memoryCache, ISettingService settingService)
        {
            _memoryCache = memoryCache;
            _settingService = settingService;
        }

        public async Task<IActionResult> Index()
        {
            var model = new SettingsIndexModel
            {
                AllInclusivePrice = await _memoryCache.GetAllInclusivePrice(_settingService),
                BreakfastPrice = await _memoryCache.GetBreakfastPrice(_settingService),
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(SettingsIndexModel model)
        {
            await _settingService.UpdateAsync("AllInclusivePrice", 
                                             model.AllInclusivePrice.ToString(),
                                             typeof(double).ToString());
            await _settingService.UpdateAsync("BreakfastPrice", 
                                             model.BreakfastPrice.ToString(),
                                             typeof(double).ToString());

            _memoryCache.ClearPriceCache();

            TempData["Success"] = true;

            return RedirectToAction(nameof(Index));
        }

    }
}

Web/Views/Shared/_Layout.cshtml
@using Data.Model
@using Microsoft.AspNetCore.Mvc.TagHelpers
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HMS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                        </li>
                        @if (SignInManager.Context.User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservations</a>
                            </li>
                        }
                        @if (SignInManager.Context.User.IsInRole("Admin") || SignInManager.Context.User.IsInRole("Employee"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Employees</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                            </li>
                        }
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - HotelReservationsManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

Web/Views/Shared/_PaginationPartial.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model PageViewModel

@{
    var searchString = Context.Request.Query["search"].ToString();
    var pageItems = Context.Request.Query["pageSize"].ToString();
}
<nav>
    <ul class="pagination justify-content-center" style="padding-top:30px; margin-bottom:0px;">
        @if (Model.CurrentPage > 1)
        {
            <li class="page-item">
                <a class="page-link"
                   asp-controller="@Model.Controller"
                   asp-action="@Model.Action"
                   asp-route-id="@(Model.CurrentPage - 1)"
                   asp-route-search="@searchString"
                   asp-route-pageSize="@pageItems"
                   aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        }
        @{
            const int MorePagesToShow = 3;
            var pagesToShow = new List<int>();

            for (var i = 1; i <= MorePagesToShow; i++)
            {
                pagesToShow.Add(i);
            }
            for (var i = Model.CurrentPage - MorePagesToShow; i <= Model.CurrentPage + MorePagesToShow; i++)
            {
                if (i > 0)
                {
                    pagesToShow.Add(i);
                }
            }
            for (var i = Model.PagesCount - MorePagesToShow + 1; i <= Model.PagesCount; i++)
            {
                if (i > 0)
                {
                    pagesToShow.Add(i);
                }
            }
            pagesToShow = pagesToShow.Where(x => x <= Model.PagesCount).Distinct().OrderBy(x => x).ToList();
        }
        @for (var i = 0; i < pagesToShow.Count; i++)
        {
            var className = string.Empty;
            var pageNumber = pagesToShow[i];
            if (pageNumber == Model.CurrentPage)
            {
                className = "active";
            }
            if (i > 0 && pageNumber - 1 != pagesToShow[i - 1])
            {
                <li class="page-item @className">
                    <a class="page-link"
                       asp-controller="@Model.Controller"
                       asp-action="@Model.Action"
                       asp-route-id="@(pagesToShow[i - 1] + 1)"
                       asp-route-search="@searchString"
                       asp-route-pageSize="@pageItems">...
                    </a>
                </li>
            }
            <li class="page-item @className">
                <a class="page-link"
                   asp-controller="@Model.Controller"
                   asp-action="@Model.Action"
                   asp-route-id="@pageNumber"
                   asp-route-search="@searchString"
                   asp-route-pageSize="@pageItems">
                    @pageNumber
                </a>
            </li>
        }
        @if (Model.CurrentPage < Model.PagesCount)
        {
            <li class="page-item">
                <a class="page-link"
                   asp-controller="@Model.Controller"
                   asp-action="@Model.Action"
                   asp-route-id="@(Model.CurrentPage + 1)"
                   asp-route-search="@searchString"
                   asp-route-pageSize="@pageItems"
                   aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        }

    </ul>
</nav>

<nav>
    <div class="d-flex justify-content-center" style="padding-top:30px; margin-bottom:0px;">
        <p class="align-items-center align-self-center mx-2 mb-0" >Elements on page: </p>
        <ul class="pagination justify-content-center mb-0">
            @{
            if (string.IsNullOrWhiteSpace(pageItems))
            {
                pageItems="10";
            }
                var curPageSize = int.Parse(pageItems);
                var classNameSize = "";
            }

            @if (curPageSize == 10)
            {
                classNameSize = "active";
            }
            <li class="page-item @classNameSize">
                <a class="page-link"
                   asp-controller="@Model.Controller"
                   asp-action="@Model.Action"
                   asp-route-id="1"
                   asp-route-search=""
                   asp-route-pageSize="10"
                   aria-label="10">
                    <span aria-hidden="true">10</span>
                </a>
            </li>

            @if (curPageSize == 20)
            {
                classNameSize = "active";
            }
            else
            {
                classNameSize = "";
            }
            <li class="page-item @classNameSize">
                <a class="page-link"
                   asp-controller="@Model.Controller"
                   asp-action="@Model.Action"
                   asp-route-id="1"
                   asp-route-search=""
                   asp-route-pageSize="20"
                   aria-label="20">
                    <span aria-hidden="true">20</span>
                </a>
            </li>

            @if (curPageSize == 50)
            {
                classNameSize = "active";
            }
            else
            {
                classNameSize = "";
            }

            <li class="page-item @classNameSize">
                <a class="page-link"
                   asp-controller="@Model.Controller"
                   asp-action="@Model.Action"
                   asp-route-id="1"
                   asp-route-search=""
                   asp-route-pageSize="50"
                   aria-label="50">
                    <span aria-hidden="true">50</span>
                </a>
            </li>
        </ul >
    </div>
</nav>